/**
 * Luna classifier prompt, assembled ONLY from (a) text copied by reference from the existing Jev
 * definitions in src/lib/sms-classification/questions.ts (never retyped) and (b) a small, explicit
 * list of NON-verbatim sentences. Governance rule: no LLM may add, edit, merge, replace or remove a
 * business rule unless a human approved that exact text. Every non-verbatim sentence below is
 * therefore listed (NON_VERBATIM) and in the PR body for Jarrad to approve. DRAFT, replay comparison
 * only: nothing here is wired into any production path.
 */
import { buildQuestions, OUTCOME_CRITERIA } from "../../../../src/lib/sms-classification/questions";
import type { JevOutcome } from "../../../../src/lib/sms-classification/types";

export const LUNA_OUTCOMES = Object.keys(OUTCOME_CRITERIA) as JevOutcome[];
const Q = buildQuestions(false);
export const LUNA_ESCALATION_REASONS = Object.keys(Q.escalation_reason.criteria);

export type PromptSegment = { text: string; verbatim: boolean; source?: string };

/** Non-verbatim sentences, in prompt order. These are the ONLY words not copied from the codebase. */
export const NON_VERBATIM = {
  role: "You are classifying the latest inbound text message in a two-way real-estate SMS conversation between a wholesaler and a property seller.",
  task: "Answer the outcome question and the escalation_reason question below, choosing exactly one option for each, using only the definitions given.",
  outcomeHeader: "Outcome options (name: definition):",
  escalationHeader: "Escalation reason options (name: definition):",
  format: "Respond with JSON only, matching the supplied schema: the chosen outcome, the chosen escalation_reason, and a confidence number from 0 to 1 for the chosen outcome.",
  userHeader: "Conversation, oldest first (the last line is the message to classify):",
} as const;

export function lunaSystemSegments(): PromptSegment[] {
  const seg: PromptSegment[] = [
    { text: NON_VERBATIM.role, verbatim: false },
    { text: NON_VERBATIM.task, verbatim: false },
    { text: Q.outcome.instructions, verbatim: true, source: "questions.ts buildQuestions().outcome.instructions" },
    { text: NON_VERBATIM.outcomeHeader, verbatim: false },
  ];
  for (const name of LUNA_OUTCOMES) {
    seg.push({ text: `${name}: ${OUTCOME_CRITERIA[name]}`, verbatim: true, source: `questions.ts OUTCOME_CRITERIA.${name} (line = "<name>: " + verbatim definition)` });
  }
  seg.push({ text: Q.escalation_reason.instructions, verbatim: true, source: "questions.ts buildQuestions().escalation_reason.instructions" });
  seg.push({ text: NON_VERBATIM.escalationHeader, verbatim: false });
  for (const [name, def] of Object.entries(Q.escalation_reason.criteria)) {
    seg.push({ text: `${name}: ${def}`, verbatim: true, source: `questions.ts escalation_reason.criteria.${name} (line = "<name>: " + verbatim definition)` });
  }
  seg.push({ text: NON_VERBATIM.format, verbatim: false });
  return seg;
}

export function lunaSystemPrompt(): string {
  return lunaSystemSegments().map((s) => s.text).join("\n\n");
}

export type ThreadLine = { direction: "inbound" | "outbound"; body: string };

/** Conversation as the user message. Role labels are structure, not business rules. */
export function lunaUserPrompt(thread: readonly ThreadLine[]): string {
  return [NON_VERBATIM.userHeader, ...thread.map((m) => `[${m.direction}] ${m.body}`)].join("\n");
}

export const LUNA_BANNER = "DRAFT — not approved; replay comparison only";

/** The reviewable artifact written to luna-prompt.md (kept in sync by a unit test). */
export function renderLunaPromptMarkdown(): string {
  const nonVerbatim = Object.values(NON_VERBATIM);
  return [
    `# ${LUNA_BANNER}`,
    "",
    "Luna classifier prompt for `npm run replay:compare`. Generated by `npm run replay:luna-prompt`; do not hand-edit.",
    "Every definition below is copied by reference from `src/lib/sms-classification/questions.ts`.",
    "The sentences listed under \"Not verbatim\" are the only words not copied from the codebase and need human approval before this is anything but a local experiment.",
    "",
    "## System prompt (exact text sent)",
    "",
    "```text",
    lunaSystemPrompt(),
    "```",
    "",
    "## User message template",
    "",
    "```text",
    `${NON_VERBATIM.userHeader}\n[inbound|outbound] <message body>\n...`,
    "```",
    "",
    "## Not verbatim (needs approval)",
    "",
    ...nonVerbatim.map((s, i) => `${i + 1}. ${s}`),
    "",
    "## Output schema (structural, no business rules)",
    "",
    "```json",
    JSON.stringify(lunaJsonSchema(), null, 2),
    "```",
    "",
  ].join("\n");
}

/** Strict JSON schema for the structured output. Enums come from the Jev code, not retyped. */
export function lunaJsonSchema() {
  return {
    type: "object",
    additionalProperties: false,
    required: ["outcome", "escalation_reason", "confidence"],
    properties: {
      outcome: { type: "string", enum: [...LUNA_OUTCOMES] },
      escalation_reason: { type: "string", enum: [...LUNA_ESCALATION_REASONS] },
      confidence: { type: "number" },
    },
  };
}
