import {beforeEach,expect,it,vi} from 'vitest';
const h=vi.hoisted(()=>({roster:vi.fn(),db:vi.fn(),hangup:vi.fn(),company:vi.fn(),rows:{} as Record<string,unknown>}));
vi.mock('server-only',()=>({}));
vi.mock('@/lib/my-leads/queries',()=>({getAcquisitionRoster:h.roster}));
vi.mock('./database',()=>({createDialpadVoiceAdminClient:h.db}));
vi.mock('./client',()=>({DialpadVoiceClient:class{getCompany=h.company;hangupCall=h.hangup;}}));
import {hangupConfiguredDialpadCall}from'./configured-hangup';
const id='11111111-1111-4111-8111-111111111111';
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('DIALPAD_VOICE_HANGUP_ENABLED','true');vi.stubEnv('DIALPAD_HISTORICAL','fixture');
h.roster.mockResolvedValue({viewer:{orgId:id,userId:id},roster:{settings:{enabled:false},members:[{id,active:true,acquisitionsEnabled:false}]}});
h.company.mockResolvedValue({id:'201'});h.hangup.mockResolvedValue({});
h.rows={dialpad_voice_intents:{id,org_id:id,actor_user_id:id,dialpad_user_id:'301',property_id:id,provider_call_id:'401'},call_activities:{org_id:id,operator_user_id:id,property_id:id,provider:'dialpad',provider_call_id:'401',provider_ended_at:null},dialpad_intent_configuration:{org_id:id,intent_id:id,connection_id:id,connection_version:1},dialpad_connection_revisions:{org_id:id,connection_id:id,config_version:1,provider_company_id:'201',credential_reference:'env:DIALPAD_HISTORICAL'}};
h.db.mockReturnValue({from:(table:string)=>{const chain={select:()=>chain,eq:()=>chain,maybeSingle:async()=>({data:h.rows[table]})};return chain;}});
});
it('uses frozen history even with new acquisitions disabled and no active grant lookup',async()=>{expect(await hangupConfiguredDialpadCall({intentId:id})).toEqual({ok:true,status:'hangup_requested'});expect(h.hangup).toHaveBeenCalledExactlyOnceWith('401');});
it.each(['org_id','actor_user_id'])('rejects wrong intent %s before provider access',async field=>{h.rows.dialpad_voice_intents={...(h.rows.dialpad_voice_intents as object),[field]:'22222222-2222-4222-8222-222222222222'};expect(await hangupConfiguredDialpadCall({intentId:id})).toEqual({ok:false,error:'bound_call_required'});expect(h.company).not.toHaveBeenCalled();expect(h.hangup).not.toHaveBeenCalled();});
it('candidate without authoritative binding is insufficient',async()=>{h.rows.dialpad_voice_intents={...(h.rows.dialpad_voice_intents as object),provider_call_id:null};expect((await hangupConfiguredDialpadCall({intentId:id})).ok).toBe(false);expect(h.hangup).not.toHaveBeenCalled();});
it('rejects wrong activity actor',async()=>{h.rows.call_activities={...(h.rows.call_activities as object),operator_user_id:'other'};expect((await hangupConfiguredDialpadCall({intentId:id})).ok).toBe(false);expect(h.hangup).not.toHaveBeenCalled();});
it('terminal call skips all provider requests',async()=>{h.rows.call_activities={...(h.rows.call_activities as object),provider_ended_at:'2026-09-14T00:00:00Z'};expect(await hangupConfiguredDialpadCall({intentId:id})).toEqual({ok:true,status:'already_ended'});expect(h.company).not.toHaveBeenCalled();expect(h.hangup).not.toHaveBeenCalled();});
it('uncertain HTTP sends once and never fabricates terminal state',async()=>{h.hangup.mockRejectedValue(new Error('timeout'));expect(await hangupConfiguredDialpadCall({intentId:id})).toEqual({ok:true,status:'hangup_unconfirmed'});expect(h.hangup).toHaveBeenCalledTimes(1);});
it('rejects company mismatch before mutation',async()=>{h.company.mockResolvedValue({id:'999'});expect((await hangupConfiguredDialpadCall({intentId:id})).ok).toBe(false);expect(h.hangup).not.toHaveBeenCalled();});
it('inactive actor cannot end calls',async()=>{h.roster.mockResolvedValue({viewer:{orgId:id,userId:id},roster:{members:[{id,active:false}]}});expect(await hangupConfiguredDialpadCall({intentId:id})).toEqual({ok:false,error:'forbidden'});});
