import { useState } from "react";
import { beforeEach,afterEach,describe,it,expect,vi } from "vitest";
import { render,screen,fireEvent,cleanup,waitFor,within } from "@testing-library/react";
import { InboxWorkspace,type InboxWorkspaceProps,type WorkspaceRow } from "./inbox-workspace";
import { workspaceId,type WorkspaceId } from "./selection";
const rows:WorkspaceRow[]=Array.from({length:120},(_,i)=>({target:{kind:"conversation",orgId:"test-org",conversationId:String(i)},name:`Person ${i}`,context:`Property ${i}`,preview:"Message preview",timeLabel:"Now",outcomeLabel:"Existing outcome",assignedLabel:"Unassigned"}));
const ids=rows.map((r)=>workspaceId(r.target));
const select=vi.fn(),action=vi.fn(),open=vi.fn();
const props=():InboxWorkspaceProps=>({scopeLabel:"Synthetic tenant",rows,selectedIds:[ids[0],ids[1]],openId:null,onSelectionChange:select,onOpen:open,onCloseDetail:vi.fn(),onBack:vi.fn(),onReviewSelection:vi.fn(),actions:[{id:"prepare",label:"Review action"}],onAction:action,connection:{state:"live",label:"Fixture only"}});
function Controlled({overrides={}}:{overrides?:Partial<InboxWorkspaceProps>}){const [selected,setSelected]=useState<readonly WorkspaceId[]>([ids[0],ids[1]]);const [opened,setOpened]=useState<WorkspaceId|null>(null);return <InboxWorkspace {...props()} selectedIds={selected} openId={opened} detail={{targetId:opened??ids[0],title:"Inspected conversation",state:"ready",content:<textarea aria-label="Detail text"/>}} onSelectionChange={(v)=>{select(v);setSelected(v);}} onOpen={(id)=>{open(id);setOpened(id);}} onCloseDetail={()=>setOpened(null)} {...overrides}/>;}
beforeEach(()=>{
 vi.clearAllMocks();
 vi.spyOn(HTMLElement.prototype,"getBoundingClientRect").mockImplementation(function(this:HTMLElement){const index=this.dataset.workspaceRow?Number(JSON.parse(this.dataset.workspaceRow)[2]):0;return {x:0,y:index*72,left:0,top:index*72,width:900,height:this.dataset.workspaceRow?72:600,right:900,bottom:this.dataset.workspaceRow?index*72+72:600,toJSON:()=>({})};});
 Object.defineProperty(HTMLElement.prototype,"offsetHeight",{configurable:true,get(){return 600;}});
 Object.defineProperty(HTMLElement.prototype,"offsetWidth",{configurable:true,get(){return 900;}});
 // jsdom lacks PointerEvent; preserve pointer identity while exercising real handlers.
 class Pointer extends MouseEvent{pointerId:number;pointerType:string;constructor(type:string,init:PointerEventInit){super(type,init);this.pointerId=init.pointerId??1;this.pointerType=init.pointerType??"mouse";}}
 vi.stubGlobal("PointerEvent",Pointer);
});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe("controlled virtual Inbox workspace",()=>{
 it("renders a bounded viewport with the real virtualizer and offers checkbox exception removal",()=>{render(<Controlled/>);expect(screen.getAllByRole("listitem").length).toBeLessThan(rows.length);fireEvent.click(screen.getByRole("checkbox",{name:"Select Person 1"}));expect(select).toHaveBeenLastCalledWith([ids[0]]);expect(open).not.toHaveBeenCalled();});
 it("plain click selects one, Shift-click adds/removes, and Open never changes selection",()=>{render(<Controlled/>);fireEvent.click(screen.getByText("Person 0"));expect(select).toHaveBeenLastCalledWith([ids[0]]);fireEvent.click(screen.getByText("Person 2"),{shiftKey:true});expect(select).toHaveBeenLastCalledWith([ids[0],ids[2]]);fireEvent.click(screen.getByText("Person 0"),{shiftKey:true});expect(select).toHaveBeenLastCalledWith([ids[2]]);select.mockClear();fireEvent.click(screen.getByRole("button",{name:"Open Person 0"}));expect(open).toHaveBeenCalledWith(ids[0]);expect(select).not.toHaveBeenCalled();});
 it("Enter inspects and Close restores focus without selecting or marking read",async()=>{render(<Controlled/>);const row=screen.getByRole("listitem",{name:/Person 0, selected/});row.focus();fireEvent.keyDown(row,{key:"Enter"});expect(open).toHaveBeenCalledWith(ids[0]);expect(select).not.toHaveBeenCalled();expect(screen.getByRole("button",{name:"Close conversation details"})).toHaveFocus();fireEvent.click(screen.getByRole("button",{name:"Close conversation details"}));await waitFor(()=>expect(screen.getByRole("button",{name:"Open Person 0"})).toHaveFocus());});
 it("Shift rectangle adds rows and Escape restores the baseline without a trailing click",()=>{render(<Controlled/>);const list=screen.getByRole("list");fireEvent.pointerDown(screen.getByText("Person 0"),{pointerId:1,button:0,shiftKey:true,clientX:10,clientY:10});fireEvent.pointerMove(list,{pointerId:1,clientX:600,clientY:210});expect(select.mock.lastCall?.[0]).toContain(ids[2]);fireEvent.keyDown(window,{key:"Escape"});expect(select).toHaveBeenLastCalledWith([ids[0],ids[1]]);fireEvent.pointerUp(list,{pointerId:1,clientX:600,clientY:210});fireEvent.click(screen.getByText("Person 2"));expect(select).toHaveBeenLastCalledWith([ids[0],ids[1]]);expect(action).not.toHaveBeenCalled();});
 it("click and group drop enter the same action callback; Shift drag never drops an action",()=>{render(<Controlled/>);const button=screen.getByRole("button",{name:"Review action"});fireEvent.click(button);expect(action).toHaveBeenLastCalledWith("prepare",[ids[0],ids[1]]);Object.defineProperty(document,"elementFromPoint",{configurable:true,value:()=>button});fireEvent.pointerDown(screen.getByText("Person 0"),{pointerId:1,button:0,clientX:10,clientY:10});fireEvent.pointerMove(screen.getByRole("list"),{pointerId:1,clientX:800,clientY:150});fireEvent.pointerUp(screen.getByRole("list"),{pointerId:1,clientX:800,clientY:150});expect(action).toHaveBeenCalledTimes(2);expect(action).toHaveBeenLastCalledWith("prepare",[ids[0],ids[1]]);fireEvent.pointerDown(screen.getByText("Person 0"),{pointerId:2,button:0,shiftKey:true,clientX:10,clientY:10});fireEvent.pointerMove(screen.getByRole("list"),{pointerId:2,clientX:800,clientY:150});fireEvent.pointerUp(screen.getByRole("list"),{pointerId:2,clientX:800,clientY:150});expect(action).toHaveBeenCalledTimes(2);});
 it("revoked identities cannot be restored by Escape and permission loss clears visible content",()=>{const p=props();const view=render(<InboxWorkspace {...p}/>);fireEvent.pointerDown(screen.getByText("Person 0"),{pointerId:1,button:0,shiftKey:true,clientX:10,clientY:10});view.rerender(<InboxWorkspace {...p} invalidatedIds={[ids[0]]}/>);fireEvent.keyDown(window,{key:"Escape"});expect(select).toHaveBeenLastCalledWith([ids[1]]);select.mockClear();fireEvent.pointerDown(screen.getByText("Person 1"),{pointerId:2,button:0,shiftKey:true,clientX:10,clientY:80});view.rerender(<InboxWorkspace {...p} connection={{state:"permission_lost",label:"Access removed"}}/>);fireEvent.keyDown(window,{key:"Escape"});expect(select).not.toHaveBeenCalled();expect(screen.queryByText("Person 1")).not.toBeInTheDocument();expect(screen.getByRole("alert")).toHaveTextContent("Access removed");});
 it("freezes resident rows during a gesture and never admits a new arrival",()=>{const p=props();const view=render(<InboxWorkspace {...p}/>);fireEvent.pointerDown(screen.getByText("Person 0"),{pointerId:1,button:0,shiftKey:true,clientX:10,clientY:10});const incoming:WorkspaceRow={...rows[0],target:{kind:"conversation",orgId:"test-org",conversationId:"new"},name:"New arrival"};view.rerender(<InboxWorkspace {...p} rows={[incoming,...rows]}/>);expect(screen.queryByText("New arrival")).not.toBeInTheDocument();fireEvent.keyDown(window,{key:"Escape"});expect(screen.getByText("New arrival")).toBeInTheDocument();expect(select).toHaveBeenLastCalledWith([ids[0],ids[1]]);});
 it("updates safe row facts while preserving gesture membership and order",()=>{const p=props();const view=render(<InboxWorkspace {...p}/>);fireEvent.pointerDown(screen.getByText("Person 0"),{pointerId:1,button:0,shiftKey:true,clientX:10,clientY:10});const updated={...rows[0],preview:"Updated preview while selecting",pendingLabel:"Update confirmed"};view.rerender(<InboxWorkspace {...p} rows={[rows[1],updated,...rows.slice(2)]}/>);expect(screen.getByText("Updated preview while selecting")).toBeInTheDocument();expect(screen.getByText("Update confirmed")).toBeInTheDocument();expect(screen.getAllByRole("listitem")[0]).toHaveTextContent("Person 0");fireEvent.keyDown(window,{key:"Escape"});expect(screen.getAllByRole("listitem")[0]).toHaveTextContent("Person 1");});
 it("excludes buttons and checkboxes from rectangle initiation",()=>{const onGestureChange=vi.fn();render(<Controlled overrides={{onGestureChange}}/>);fireEvent.pointerDown(screen.getByRole("checkbox",{name:"Select Person 0"}),{pointerId:1,button:0,shiftKey:true,clientX:10,clientY:10});fireEvent.pointerMove(screen.getByRole("list"),{pointerId:1,clientX:600,clientY:220});fireEvent.pointerUp(screen.getByRole("list"),{pointerId:1,clientX:600,clientY:220});expect(onGestureChange).not.toHaveBeenCalled();expect(select).not.toHaveBeenCalled();fireEvent.pointerDown(screen.getByRole("button",{name:"Open Person 0"}),{pointerId:2,button:0,shiftKey:true});expect(onGestureChange).not.toHaveBeenCalled();});
 it("never drops onto another workspace instance with the same action ID",()=>{const first=props(),second=props();second.scopeLabel="Other instance";second.onAction=vi.fn();render(<><InboxWorkspace {...first}/><InboxWorkspace {...second}/></>);const a=within(screen.getByRole("region",{name:"Inbox workspace: Synthetic tenant"}));const b=within(screen.getByRole("region",{name:"Inbox workspace: Other instance"}));Object.defineProperty(document,"elementFromPoint",{configurable:true,value:()=>b.getByRole("button",{name:"Review action"})});fireEvent.pointerDown(a.getByText("Person 0"),{pointerId:1,button:0,clientX:10,clientY:10});fireEvent.pointerMove(a.getByRole("list"),{pointerId:1,clientX:800,clientY:150});fireEvent.pointerUp(a.getByRole("list"),{pointerId:1,clientX:800,clientY:150});expect(action).not.toHaveBeenCalled();expect(second.onAction).not.toHaveBeenCalled();});
 it("does not render a late response for a different opened target",()=>{render(<InboxWorkspace {...props()} openId={ids[1]} detail={{targetId:ids[0],title:"Old conversation",state:"ready",content:"Private stale history"}}/>);expect(screen.queryByText("Private stale history")).not.toBeInTheDocument();expect(screen.getByText("Loading conversation…")).toBeInTheDocument();});
 it("does not call unloaded selections outside a filter and disables pending actions",()=>{render(<Controlled overrides={{rows:rows.slice(0,1),actions:[{id:"prepare",label:"Review action",pending:true}]}}/>);expect(screen.getByText(/1 not loaded here/)).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:/Review action/}));expect(action).not.toHaveBeenCalled();});
});
