export const MAX_RECOMMENDATION_TRANSCRIPT_LINES = 40;
export const MAX_RECOMMENDATION_TRANSCRIPT_CHARS = 12_000;
export const FOLLOW_UP_RECOMMENDATION_LIMIT_PER_CALL = 20;
export const OBJECTION_HELP_LIMIT_PER_CALL = 20;
