/**
 * Build script: generate supabase/migrations/040_seed_bmh_sms_templates.sql
 * from docs/sms-templates.md.
 *
 * Usage:
 *   npx tsx scripts/build-sms-template-seed.ts
 */

import fs from "node:fs";
import path from "node:path";
import { parseSeedBlock, validateRows } from "../src/lib/templates/seed-builder";

const ROOT = path.resolve(__dirname, "..");
const MD_PATH = path.join(ROOT, "docs", "sms-templates.md");
const OUT_PATH = path.join(ROOT, "supabase", "migrations", "040_seed_bmh_sms_templates.sql");
const EXPECTED_ROW_COUNT = 43;

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

function main() {
  const markdown = fs.readFileSync(MD_PATH, "utf-8");

  const parsed = parseSeedBlock(markdown);
  if (!parsed.ok) {
    console.error(`ERROR: ${parsed.error}`);
    process.exit(1);
  }

  const { rows } = parsed;
  console.log(`Parsed ${rows.length} rows from seed block.`);

  if (rows.length !== EXPECTED_ROW_COUNT) {
    console.error(
      `ERROR: Expected ${EXPECTED_ROW_COUNT} rows, got ${rows.length}. ` +
        `Update EXPECTED_ROW_COUNT in this script if you added/removed templates.`,
    );
    process.exit(1);
  }

  const errors = validateRows(rows);
  if (errors.length > 0) {
    console.error("Validation errors:");
    for (const e of errors) {
      console.error(`  Row ${e.row} ("${e.name}"): ${e.issues.join("; ")}`);
    }
    process.exit(1);
  }

  console.log("Validation passed. Generating SQL...");

  const valueLines = rows
    .map(
      (r) =>
        `  (v_org_id, '${esc(r.name)}', '${esc(r.content)}', '${esc(r.category)}', true)`,
    )
    .join(",\n");

  const sql = `-- Auto-generated by scripts/build-sms-template-seed.ts — do not edit by hand.
-- Re-run: npx tsx scripts/build-sms-template-seed.ts

DO $$
DECLARE
  v_org_id uuid;
BEGIN
  SELECT id INTO v_org_id FROM public.organizations WHERE name = 'BMH Group' LIMIT 1;
  IF v_org_id IS NULL THEN
    RAISE NOTICE 'BMH Group org not found — skipping template seed';
    RETURN;
  END IF;

  INSERT INTO public.sms_templates (org_id, name, content, category, system_managed) VALUES
${valueLines}
  ON CONFLICT (org_id, name) DO NOTHING;
END;
$$;
`;

  fs.writeFileSync(OUT_PATH, sql, "utf-8");
  console.log(`Written to ${OUT_PATH}`);
}

main();
