import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { artifactHashes, assertCleanStart, assertOnlyRunDirDirty, runPath, sha256, writeManifest } from './outbox-run-record.mjs';
function repo() { const dir = mkdtempSync(path.join(tmpdir(), 'outbox-record-')); execFileSync('git', ['init', '-q', dir]); execFileSync('git', ['-C', dir, 'config', 'user.email', 'test@example.invalid']); execFileSync('git', ['-C', dir, 'config', 'user.name', 'Test']); writeFileSync(path.join(dir, 'tracked'), 'baseline'); execFileSync('git', ['-C', dir, 'add', '.']); execFileSync('git', ['-C', dir, 'commit', '-qm', 'baseline']); return dir; }
test('layout and artifact hashes', () => { const dir = repo(); const sha = execFileSync('git', ['-C', dir, 'rev-parse', 'HEAD'], {encoding:'utf8'}).trim(); const relative = runPath(sha, 'pre-merge', 'run_1'); const full = path.join(dir, relative); mkdirSync(full, {recursive:true}); writeFileSync(path.join(full,'results.json'), 'hello'); assert.deepEqual(artifactHashes(full), {'results.json':'2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824'}); const manifest = writeManifest(dir, relative, { tested_sha:sha }); assert.equal(manifest.artifacts['results.json'], sha256('hello')); assert.equal(JSON.parse(readFileSync(path.join(full,'manifest.json'))).tested_sha, sha); assertOnlyRunDirDirty(dir, relative); });
test('dirty tree refusal and exact run-dir exclusion', () => { const dir = repo(); assertCleanStart(dir); writeFileSync(path.join(dir,'stray'), 'x'); assert.throws(() => assertCleanStart(dir), /dirty tree/); assert.throws(() => assertOnlyRunDirDirty(dir, 'docs/performance/inbox-redesign/evidence/abc'), /Non-record/); });
test('path rejects malformed SHA, tier, and run ID', () => { assert.throws(() => runPath('short','pre-merge','id')); assert.throws(() => runPath('a'.repeat(40),'other','id')); assert.throws(() => runPath('a'.repeat(40),'pre-merge','../escape')); });
test('end attestation rejects a sibling evidence run', () => { const dir = repo(); const allowed = runPath('a'.repeat(40), 'pre-merge', 'run_1'); const sibling = runPath('a'.repeat(40), 'pre-merge', 'run_2'); mkdirSync(path.join(dir, allowed), {recursive:true}); writeFileSync(path.join(dir, allowed, 'results.json'), '{}'); mkdirSync(path.join(dir, sibling), {recursive:true}); writeFileSync(path.join(dir, sibling, 'results.json'), '{}'); assert.throws(() => assertOnlyRunDirDirty(dir, allowed), /Non-record/); });
