-- Auto-generated by scripts/build-sms-template-seed.ts — do not edit by hand.
-- Re-run: npx tsx scripts/build-sms-template-seed.ts

DO $$
DECLARE
  v_org_id uuid;
BEGIN
  SELECT id INTO v_org_id FROM public.organizations WHERE name = 'BMH Group' LIMIT 1;
  IF v_org_id IS NULL THEN
    RAISE NOTICE 'BMH Group org not found — skipping template seed';
    RETURN;
  END IF;

  INSERT INTO public.sms_templates (org_id, name, content, category, system_managed) VALUES
  (v_org_id, 'Owner check (consensus)', 'Are you the owner of {{property_address}}?', 'Outreach - Homeowner', true),
  (v_org_id, 'Awkward owner check', '{{first_name | Hey there}}, sorry to bother. I think you might own {{property_address}}? - {{my_first_name}}', 'Outreach - Homeowner', true),
  (v_org_id, 'Random + owner check', 'Hi {{first_name | there}}, I know this is random. Looking for the owner of {{property_address}}. That you?', 'Outreach - Homeowner', true),
  (v_org_id, 'Local sender + still own', '{{first_name | Hi}}, {{my_first_name}} here in {{city | your area}}. Quick question: still own the place at {{property_address}}?', 'Outreach - Homeowner', true),
  (v_org_id, 'Soft tied-to check', 'Hey {{first_name | there}}, quick one - are you still tied to {{property_address}}? - {{my_first_name}}', 'Outreach - Homeowner', true),
  (v_org_id, 'Touch 2, bump', 'Hey {{first_name | there}}, didn''t want my last text to get buried. Still you on {{property_address}}?', 'Outreach - Homeowner', true),
  (v_org_id, 'Touch 3, soft close', '{{first_name | Hi}}, last try from me on {{property_address}}. Even a "wrong house" helps me close the loop.', 'Outreach - Homeowner', true),
  (v_org_id, 'Touch 4, re-engage', '{{first_name | Hey}}, circling back on {{property_address}}. Anything change on your end? No pressure either way.', 'Outreach - Homeowner', true),
  (v_org_id, 'Touch 5, break-up', '{{first_name | Hi}}, I''ll stop reaching out unless I hear back. Reply STOP to opt out anytime. - {{my_first_name}}', 'Outreach - Homeowner', true),
  (v_org_id, 'Reply: Who are you', '{{my_first_name}} here, local in {{city | your area}}. Small team that buys homes directly. Pulled your address from public records.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Where did you get my number', 'Fair question. Your number came up tied to {{property_address}} in public records. Want me to take you off the list?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: What''s your offer (deflect to condition)', 'Honestly depends a lot on condition. If you give me 2 min, beds/baths, any updates, I can usually get a ballpark same day.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: What''s your offer (terms variant)', 'Depends on what works for you. Are you open to flexibility on terms, or strictly looking at a cash number?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Wrong number / referral ask', 'My apologies, I''ll get you off the list right away. Quick favor though, any chance you know who owns {{property_address}}?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Not interested (date hook)', 'All good, {{first_name | thanks for letting me know}}. If anything changes in the next 6-12 months, mind if I check back?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Not interested (discovery)', 'Got it. Out of curiosity, what would have to be true for you to consider an offer? No pressure, just helpful for me to know.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: STOP confirmation', 'You''re removed, sorry for the bother. Have a good one.', 'Compliance', true),
  (v_org_id, 'Reply: Real person check', 'Real human, promise. {{my_first_name}} here. Want to hop on a quick call instead? Easier than texting.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Scam check', 'Fair question, there''s a lot of junk out there. {{my_first_name}} with {{company_name}}, local to {{city | your area}}. Happy to talk first.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Already listed', 'Got it, open to me sending a cash offer through your agent? Want to pass along their info?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Send in writing (force discovery)', 'Happy to. To put a real number on paper I''d need a few details, what kind of condition is the place in?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Owe more than worth', 'That''s actually where creative options can help. Open to a quick call to see what''d work?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Needs work', 'That''s a plus on my end, I buy as-is, no repairs on you. Care if I take a quick look this week?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Need to talk to spouse', 'Of course, take the time you need. Has selling come up between you two before? Curious what they said.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Maybe what price (range pivot)', 'Depends on condition + recent comps, usually a range until I see it. Got 5 min for a quick call so I can be specific?', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: How fast', '7-14 days, all cash. Title sets the actual date but we don''t drag our feet.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Send email', 'Will do, what''s the best email? I''ll send a one-pager and details before we talk.', 'Reply - Homeowner', true),
  (v_org_id, 'Reply: Call me', 'Absolutely, what''s a good time today or tomorrow? I''ll keep it under 5 minutes.', 'Reply - Homeowner', true),
  (v_org_id, 'Agent: Active listing post-VM', 'Hi {{first_name | there}}, {{my_first_name}} here, left you a VM on your listing at {{property_address}}. Active cash buyer locally, got 2 min?', 'Outreach - Agent', true),
  (v_org_id, 'Agent: Expired listing', 'Hi {{first_name}}, saw {{property_address}} expired. Active cash buyer in {{market | the area}}, interested if your seller is still open.', 'Outreach - Agent', true),
  (v_org_id, 'Agent: Bump', 'Hey {{first_name}}, circling back on {{property_address}}. Worth a quick chat? - {{my_first_name}}', 'Outreach - Agent', true),
  (v_org_id, 'Agent: Break-up', 'Last bump on {{property_address}}, {{first_name}}. If it''s not a fit, no worries, happy to be on your buyer list. Reply STOP to opt out.', 'Outreach - Agent', true),
  (v_org_id, 'Agent reply: Who are you with', '{{my_first_name}} with {{company_name}}, active cash buyer in {{market | your area}}. Close fast, full co-op to listing side.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Buy box', '{{market | Local}} SFR + 2-4 unit, any condition. POF available. {{property_address}} caught my eye, still active?', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Are you licensed', 'Principal buyer, not licensed. Open to dual-agency on this if you want, happy to do a buyer rep agreement either way.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Send email', 'Sure, what''s the best address? I''ll send POF, recent closings, and a number on {{property_address}}.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Multiple offers / backup', 'Understood. Worth being a backup? I close fast and don''t fall out. Either way, would love to be on your list for future inventory.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: POF', 'Sending now, what email is best? Bank letter or platform statement, your call.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Speed + contingencies', '7-14 days, no financing or appraisal contingency. Brief inspection (3-5 days) for our records, no re-trade unless something major.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Commission', 'Full co-op to listing side, paid at close per the MLS. No haggling on your fee.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Not interested', 'All good, appreciate the reply. If anything comes across that needs a fast cash close, keep me in mind.', 'Reply - Agent', true),
  (v_org_id, 'Agent reply: Offer on this one', 'Need to see condition + run comps. Can I get inside this week? Same-day written offer once I''ve walked it.', 'Reply - Agent', true),
  (v_org_id, 'First-message identification', '{{my_first_name}} with {{company_name}}. Reply STOP to opt out.', 'Compliance', true)
  ON CONFLICT (org_id, name) DO NOTHING;
END;
$$;
