import { Client } from 'pg';
import { afterAll, describe, expect, it } from 'vitest';
import {
  CALL, addLead, as, dbUrl, ingest, ledger, nativeCall, prepare, service, setFlag, world, type Json, type PgError, type World,
} from '@tests/integration/dialpad-p2-fixture';

// Concurrency proofs for the P2 data plane (native matching, assign to lead, intent timeout, artifact claim).
// Locks only conflict between COMMITTED sessions, so unlike the sibling suites (one rolled-back transaction each)
// this file needs the Phase 2 migrations already committed in the database: true in CI, where the disposable
// database is fully migrated, and locally on a scratch database built from the whole chain. Without them the file
// skips rather than failing. It seeds fresh orgs and removes them again in afterAll (superuser, triggers off):
// native ledger rows left behind would make the sibling suites' rollback of the chain fail on this database.

async function committedChain(): Promise<boolean> {
  const db = new Client({ connectionString: dbUrl() });
  await db.connect();
  try {
    const r = await db.query(`select
      to_regprocedure('public.fn_assign_native_call_to_lead(uuid,text,uuid)') is not null
      and to_regprocedure('public.dialpad_cti_native_resolve(uuid)') is not null
      and to_regprocedure('public.fn_fail_stale_dialpad_intents(integer,integer)') is not null
      and to_regprocedure('public.fn_claim_dialpad_artifact_fetches(integer,integer,text[])') is not null
      and to_regclass('public.contact_phone_numbers') is not null as ok`);
    return r.rows[0].ok === true;
  } catch {
    return false;
  } finally {
    await db.end();
  }
}
const present = await committedChain();

async function open(): Promise<Client> {
  const db = new Client({ connectionString: dbUrl() });
  await db.connect();
  await db.query('begin');
  await db.query("set local lock_timeout = '20s'");
  return db;
}
async function seeded<T>(fn: (db: Client) => Promise<T>): Promise<T> {
  const db = await open();
  try {
    const out = await fn(db);
    await db.query('commit');
    return out;
  } catch (error) {
    await db.query('rollback').catch(() => {});
    throw error;
  } finally {
    await db.end();
  }
}
const finish = async (db: Client, ok: boolean) => {
  await db.query(ok ? 'commit' : 'rollback').catch(() => {});
  await db.end();
};
const pause = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const created: { orgs: string[]; users: string[] } = { orgs: [], users: [] };
const track = (w: World): World => {
  created.orgs.push(w.org);
  created.users.push(w.owner, w.rep, w.rep2);
  return w;
};
// Deletes everything the seeded orgs own. Triggers (immutability guards) and FK checks are off for this
// transaction only, so every table with an org_id column is emptied for those orgs in any order.
afterAll(async () => {
  if (!present || created.orgs.length === 0) return;
  const db = new Client({ connectionString: dbUrl() });
  await db.connect();
  try {
    await db.query('begin');
    await db.query('set local session_replication_role = replica');
    const orgArray = `{${created.orgs.join(',')}}`; // uuids generated by this file
    await db.query(
      `do $c$ declare r record; begin
         for r in select c.table_name from information_schema.columns c
                  join information_schema.tables t on t.table_schema = c.table_schema and t.table_name = c.table_name
                  where c.table_schema = 'public' and c.column_name = 'org_id' and t.table_type = 'BASE TABLE'
         loop execute format('delete from public.%I where org_id = any(%L::uuid[])', r.table_name, '${orgArray}'); end loop;
       end $c$`,
    );
    await db.query('delete from public.organizations where id = any($1::uuid[])', [created.orgs]);
    await db.query('delete from auth.users where id = any($1::uuid[])', [created.users]);
    await db.query('commit');
  } catch (error) {
    await db.query('rollback').catch(() => {});
    throw error;
  } finally {
    await db.end();
  }
});
const onWorld = (w: World, db: Client): World => ({ ...w, db });
const counts = async (w: World) => {
  const l = await seeded(async (db) => ledger(onWorld(w, db)));
  return { intents: l.intent.length, activities: l.activity.length, attempts: l.attempt.length, l };
};

describe.skipIf(!present)('P2 data plane concurrency (needs the Phase 2 migrations committed)', () => {
  it('native matching: two sessions processing different events of one call create one intent and one attempt', async () => {
    const { w, ids } = await seeded(async (db) => {
      const w = track(await world(db, { flag: true }));
      const ids: string[] = [];
      for (const e of nativeCall(w)) ids.push(await ingest(w, e));
      return { w, ids };
    });
    const a = await open();
    const b = await open();
    let ok = false;
    try {
      await service(a, () => a.query('select public.fn_process_dialpad_call_event($1)', [ids[0]])); // holds the chain lock
      const second = service(b, () => b.query('select public.fn_process_dialpad_call_event($1)', [ids[1]]));
      await pause(300);
      await a.query('commit');
      await second;
      await b.query('commit');
      ok = true;
    } finally {
      await finish(a, false);
      await finish(b, ok);
    }
    // The third event arrives afterwards and attaches by call id.
    await seeded(async (db) => { await service(db, () => db.query('select public.fn_process_dialpad_call_event($1)', [ids[2]])); });
    const c = await counts(w);
    expect([c.intents, c.activities, c.attempts]).toEqual([1, 1, 1]);
    expect(c.l.intent[0]).toMatchObject({ origin: 'native', status: 'matched', matched_provider_call_id: CALL });
  });

  it('assign to lead: two assigns for different leads and an incoming hangup leave exactly one winner and one intent', async () => {
    const { w, other, hangupId } = await seeded(async (db) => {
      const w = track(await world(db, { flag: true }));
      const other = await addLead(w, { phone: '816-555-0142' });
      const [calling, connected, hangup] = nativeCall(w);
      await ingest(w, calling!);
      await ingest(w, connected!);
      const hangupId = await ingest(w, hangup!);
      // Process the first two so they quarantine ambiguous_lead (the hangup stays unprocessed).
      const events = (await db.query('select id from public.dialpad_call_events where org_id=$1 order by event_timestamp_ms', [w.org])).rows;
      for (const row of events.slice(0, 2)) await service(db, () => db.query('select public.fn_process_dialpad_call_event($1)', [row.id]));
      return { w, other, hangupId };
    });
    const assignSql = 'select public.fn_assign_native_call_to_lead($1,$2,$3) as v';
    const a = await open();
    const b = await open();
    const c = await open();
    let errorB: PgError | undefined;
    try {
      const first = await as(a, 'authenticated', w.rep, () => a.query(assignSql, [w.org, CALL, other.property]));
      expect(first.rows[0].v.status).toBe('assigned'); // a holds the chain lock, uncommitted
      // Each waiter finishes its own transaction as soon as its statement returns, so whichever of the two gets
      // the chain lock first releases it for the other (an aborted or idle transaction would hold it).
      const loser = (async () => {
        try {
          await as(b, 'authenticated', w.rep, () => b.query(assignSql, [w.org, CALL, w.property]));
          await b.query('commit');
        } catch (e) {
          errorB = e as PgError;
          await b.query('rollback');
        }
      })();
      const hangup = (async () => {
        await service(c, () => c.query('select public.fn_process_dialpad_call_event($1)', [hangupId]));
        await c.query('commit');
      })();
      await pause(300);
      await a.query('commit');
      await Promise.all([loser, hangup]);
    } finally {
      await finish(a, false);
      await finish(b, false);
      await finish(c, false);
    }
    expect(errorB?.code).toBe('MLS01'); // the loser sees the frozen match and is refused, not double-assigned
    const out = await counts(w);
    expect([out.intents, out.activities, out.attempts]).toEqual([1, 1, 1]);
    expect(out.l.intent[0].property_id).toBe(other.property);
    expect(out.l.activity[0].ended_at).not.toBeNull(); // the hangup attached after the assignment
  });

  it('intent timeout: a second sweep running at the same time skips locked rows and never double-updates', async () => {
    const ids = await seeded(async (db) => {
      const w = track(await world(db, { flag: true }));
      const out: string[] = [];
      for (let i = 0; i < 2; i++) {
        const intent = await prepare(onWorld(w, db));
        await db.query("update public.dialpad_call_intents set dispatch_authorized_at = now() - interval '10 minutes' where id=$1", [intent.intentId]);
        out.push(intent.intentId);
      }
      return out;
    });
    const a = await open();
    const b = await open();
    let first = 0;
    let second = -1;
    try {
      first = (await service(a, () => a.query('select public.fn_fail_stale_dialpad_intents(120) as n'))).rows[0].n; // a holds the row locks
      second = (await service(b, () => b.query('select public.fn_fail_stale_dialpad_intents(120) as n'))).rows[0].n;
      await a.query('commit');
      await b.query('commit');
    } finally {
      await finish(a, false);
      await finish(b, false);
    }
    expect(first).toBeGreaterThanOrEqual(ids.length);
    expect(second).toBe(0);
    const marked = await seeded(async (db) => (await db.query('select id, failed_at from public.dialpad_call_intents where id = any($1::uuid[])', [ids])).rows);
    expect(marked.every((r) => r.failed_at !== null)).toBe(true);
  });

  it('artifact claim: two sessions never receive the same row, and a leased row is not handed out again', async () => {
    const w = await seeded(async (db) => {
      const w = track(await world(db, { flag: true }));
      await setFlag(db, w.org, 'artifact_fetch', true);
      const started = Date.now() - 3 * 3_600_000;
      const base = { ...w, db, now: started };
      for (const e of nativeCall(base)) {
        const id = await ingest(base, e);
        await service(db, () => db.query('select public.fn_process_dialpad_call_event($1)', [id]));
      }
      return w;
    });
    const claim = (db: Client): Promise<Json[]> =>
      service(db, async () => (await db.query('select public.fn_claim_dialpad_artifact_fetches(100,120) as v')).rows[0].v);
    const mine = async (): Promise<Set<string>> =>
      seeded(async (db) => new Set((await db.query('select id from public.dialpad_call_artifact_fetches where org_id=$1', [w.org])).rows.map((r) => r.id as string)));
    const own = await mine();
    expect(own.size).toBeGreaterThan(0);
    const a = await open();
    const b = await open();
    let got: Json[] = [];
    let other: Json[] = [];
    try {
      got = await claim(a); // a holds the row locks and the leases, uncommitted
      other = await claim(b);
      await a.query('commit');
      await b.query('commit');
    } finally {
      await finish(a, false);
      await finish(b, false);
    }
    const first = new Set(got.map((r) => r.id as string));
    expect([...first].filter((id) => own.has(id))).toHaveLength(2); // transcript and recap are due; recording_link is not claimed here
    expect(other.filter((r) => first.has(r.id as string))).toEqual([]);
    const again = await seeded((db) => claim(db));
    expect(again.filter((r) => own.has(r.id as string))).toEqual([]); // leased
  });
});
