name: QUAL Upstream

on:
  workflow_dispatch:

permissions: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Complete dummy upstream run
        run: echo 'QUAL upstream completed'
